### ISSUE TITLE
Tons Measurement Incorrect

### ISSUE THREAD

**Issue by panarchist** [nathangeffen/space-travel#1]
Awesome calculator!  Really minor nitpick.  "Tons" is an Imperial measurement, and equal to 907.185kg.  The metric ton should be "Tonnes".

Thanks for building this, and also for publishing the code!

**Comment by nathangeffen** [comment]
Hi Matt

Thanks for pointing that out and for the kind words. Albeit a minor error I
would like the calculator to be accurate, so I will correct it next week.

Regards
Nathan


On 24 Feb 2017 22:18, "Matt Picio (aka panarchist)" <
notifications@github.com> wrote:

Awesome calculator! Really minor nitpick. "Tons" is an Imperial
measurement, and equal to 907.185kg. The metric ton should be "Tonnes".

Thanks for building this, and also for publishing the code!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nathangeffen/space-travel/issues/1>, or mute the thread

**Comment by nathangeffen** [comment]
Fixed 17 March, 14:05 (GMT+2).

**Comment by panarchist** [comment]
Awesome, thanks!
